// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhUr6mDIYiR_Fk5_E1AYWghw0LvwC1ac',
    appId: '1:2554347969:web:5722d4020ddeb630ab2f40',
    messagingSenderId: '2554347969',
    projectId: 'mmherbel-e416f',
    authDomain: 'mmherbel-e416f.firebaseapp.com',
    storageBucket: 'mmherbel-e416f.firebasestorage.app',
    measurementId: 'G-B4Y2V7ZH2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw6ZYKLBRj0OcEEbvFvlfeL0jrO61K0aI',
    appId: '1:2554347969:android:da7c17298086c467ab2f40',
    messagingSenderId: '2554347969',
    projectId: 'mmherbel-e416f',
    storageBucket: 'mmherbel-e416f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAL2LJBXMtCWMOWjcypDAjn0w1o-WQtD4',
    appId: '1:2554347969:ios:3c0a12eddae1b1cbab2f40',
    messagingSenderId: '2554347969',
    projectId: 'mmherbel-e416f',
    storageBucket: 'mmherbel-e416f.firebasestorage.app',
    iosBundleId: 'com.example.mmherbel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAL2LJBXMtCWMOWjcypDAjn0w1o-WQtD4',
    appId: '1:2554347969:ios:3c0a12eddae1b1cbab2f40',
    messagingSenderId: '2554347969',
    projectId: 'mmherbel-e416f',
    storageBucket: 'mmherbel-e416f.firebasestorage.app',
    iosBundleId: 'com.example.mmherbel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOhUr6mDIYiR_Fk5_E1AYWghw0LvwC1ac',
    appId: '1:2554347969:web:d4a4c04e8223b33dab2f40',
    messagingSenderId: '2554347969',
    projectId: 'mmherbel-e416f',
    authDomain: 'mmherbel-e416f.firebaseapp.com',
    storageBucket: 'mmherbel-e416f.firebasestorage.app',
    measurementId: 'G-RPQDF96E4B',
  );
}
